 {
	"items" : [
        {   "type" :         "Staff",
            "label" :        "John Zimmerman",
            "building" :     "Armory",
            "campus" :	   "CUMC",
            "room" :	   "200 Level",
            "email" :        "zim@columbia.edu",
            "last" :         "Zimmerman",
            "first" :	   "John",
            "phone" :        "646 772-8607",
            "title" :        "Associate Director",
            "group" :	    "Management",
            "bio" :	    "Dr. Zimmerman manages the Health Sciences office of CCNMTL, working with a dedicated Health Sciences-CCNMTL staff and faculty at all of the Health Sciences Schools to develop course Web sites and major projects. As Assistant Dean for Information Resources, Associate Professor of Clinical Dentistry at Columbia University School of Dental and Oral Surgery and Associate Professor of Clinical Medical Informatics in the College of Physicians and Surgeons, Dr. Zimmerman coordinates the clinical, research, and educational informatics initiatives at the dental school and is director of the Dental Informatics Fellowship program.  He has published numerous dental informatics articles as well as the book _Dental Informatics: Integrating Technology into the Dental Environment_ and the monograph _Dental Informatics: Strategic Issues for the Dental Profession_. Dr. Zimmerman has been active in the field of dental information for many years and is the founder of American Medical Informatics Association's Working Group 4 - Dental Informatics and a member of the International Medical Informatics Association, Working Group 11- Dental Informatics. He was the first dentist elected to American College of Medical Informatics.",
            "imageURL" :      "http://ccnmtl.columbia.edu/web/assets/headshots/Zimmerman.jpg"     
        },
        {   "type" :          "Staff",
            "label" :         "Marc Raymond",
            "building" :      "Butler Library",
            "campus" :	    "Morningside",
            "room" :	    "505",
            "email" :         "mraymond@columbia.edu",
            "last" :          "Raymond",
            "first" :	    "Marc",
            "phone" :         "212 854-1866",
            "title" :         "Webmaster",
            "group" :	    "Editorial and Design",
            "bio" :	    "Marc is responsible for the conception, planning and execution of many of the dynamic, inviting, and user-friendly Web sites that CCNMTL produces.  Prior to working at CCNMTL, Marc provided Art Direction and Web Development services for the New York City-based Web development companies CollabNet and cdINK. From 1998 to 2000, he was Senior Web Developer of the Web Design Group for Earthlink, Inc. in Atlanta, Georgia. He has designed and developed Web sites for Turner Networks, Oracle, Madison Magazine, Welborn Henson, Catalyst Magazine, and the High Museum of Art in Atlanta, among others. Marc received his B.A. in Telecommunications/Film Studies from Rhode Island College in Providence, Rhode Island.",
            "imageURL" :      "http://ccnmtl.columbia.edu/web/assets/headshots/Raymond.jpg"     
        },
        {   "type" :          "Staff",
            "label" :         "A. Maurice Matiz",
            "building" :      "Butler Library",
            "campus" :	    "Morningside",
            "room" :	    "505A",
            "email" :         "maurice@columbia.edu",
            "last" :          "Matiz",
            "first" :	    "Maurice",
            "phone" :         "212 854-2665",
            "title" :         "Vice Executive Director, Director of Technology",
            "group" :	    ["Management", "Technology"],
            "bio" :	    "Maurice is a co-founder of the Columbia Center for New Media Teaching and Learning and currently plans and oversees its direction, focusing primarily on technical, design, and operational issues. Maurice's work and interest has focused on the use of video in multimedia environments and in the use of dynamic, database-driven information. His role at CCNMTL is a natural evolution of his work at Columbia's Academic Information Systems (AcIS), where for more than a decade he led the Academic Technologies Group. There, Maurice was involved in a number of initiatives, such as the University's first electronic classroom project and the Sonic Glossary, a musical reference tool. These projects captured his interest in educational technology and led to his involvement in the creation of CCNMTL in 1999. Before joining Columbia University, Maurice worked on the Trident submarine missile project at General Dynamics Corporation, which designs and manufactures defense systems for government use.  Maurice has a B.S. ('79) and an M.S. ('82) in Computer Science from the School of Engineering and Applied Science at Columbia University.",
            "imageURL" :      "http://ccnmtl.columbia.edu/web/assets/headshots/Matiz.jpg"
        },
        {   "type" :          "Staff",
            "label" :         "Gerard Zoehfeld",
            "building" :            	"Butler Library",
            "campus" :			"Morningside",
            "room" :				"505",
            "email" :         "zoehfeld@columbia.edu",
            "last" :       	"Zoehfeld",
            "first" :			"Gerard",
            "phone" :         "212 854-1462",
            "title" :         "Digital Media Specialist",
            "group" : 		"Digital Media",
            "bio" : 			"As Digital Media Specialist, Gerard integrates digital audio and video with a variety of new media applications to enhance their use for classroom presentation and study.  Prior to joining CCNMTL, he worked as a live events sound designer, in venues such as Symphony Space, Town Hall, St. Ann's Brooklyn, Washington Square Church, The New School and the Prospect Park Bandshell. He became more interested in Audio for Video than live sound and started designing and editing for film and video in both the independent film and cable television arenas. Gerard graduated from New York University's School of Education with a Bachelors of Music with a concentration in Acoustics and Technology. He is currently working towards his MA in Anthropology at Columbia's Graduate School of Arts and Sciences.",
            "imageURL" :              "http://ccnmtl.columbia.edu/web/assets/headshots/Zoehfeld.jpg"
        },
        {   "type" :          "Staff",
            "label" :         "John Frankfurt",
            "building" :            	"Butler Library",
            "campus" :			"Morningside",
            "room" :				"505",
            "email" :         "jmf@columbia.edu",
            "last" :       	"Frankfurt",
            "first" :			"John",
            "phone" :          "212 854-1865",
            "title" :          "Educational Technologist I",
            "group" : 		 "Education",
            "bio" : 			"Frankfurt has been working with CCNMTL since 2001.  During this time, he was in charge of content development for the e-seminars Shoenberg and the Modern Age (2001) and Art & Understanding (2002) as well as the multimedia study environment of Salman Rushdie's Midnight's Children (2003).  He was the assistant project manager for The Autobiography of Malcolm X multimedia study environment (2004) and the project manager for the Art & Technology Lectures (2004), the online learning environment for Peter Brook's Tierno Bokar (2005), the Social Justice Movements wiki (2005) as well as the African-American Poets wiki (2006).  Currently, he is the project manager for  the Film Language Glossary (ongoing), Columbia Artists/Teachers wiki (ongoing), V&aacute;clav Havel at Columbia (2006) and the Harlem Digital Archive (2007). In addition to working at CCNMTL, Frankfurt is an Adjunct Assistant Professor at Columbia's Film Division in the School of the Arts and Hunter College's Department of Film & Media.",
            "imageURL" :              "http://ccnmtl.columbia.edu/web/assets/headshots/Frankfurt.jpg"
        },
        {   "type" :          "Staff",
            "label" :         "Brian O'Hagan",
            "building" :            	"Butler Library",
            "campus" :			"Morningside",
            "room" :				"505",
            "email" :         "bo2004@columbia.edu",
            "last" :       	"O'Hagan",
            "first" :			"Brian",
            "phone" :          "212 854-4429",
            "title" :          "Digital Media Technologist",
            "group" : 		  "Digital Media",
            "bio" : 			"Brian is a part of the video group at the Center for New Media Teaching and Learning, where he researches, develops and documents Web-based video technologies, media distribution, and interactive presentations.  He also coordinates the post-production of project-specific Web media assets and works with programmers and webmasters to implement audio and video modules.  For the past 3 years, he has also been the quality assurance developer on CCNMTL projects. Brian has hosted and contributed to numerous workshops on video editing, Web video formats, podcasting, and blogging. Brian came to CCNMTL in 2001.  He studied history at the University of Louisville, and his interest in film, technology and video led to his current work with digital media development.  In his free time, he likes to keep up to date with emerging social technology trends, Internet and gaming theory, as well as assorted gadgetry. ",
            "imageURL" :              "http://ccnmtl.columbia.edu/web/assets/headshots/O'Hagan.jpg"
        },
        {   "type" :          "Staff",
            "label" :         "Jonah Bossewitch",
            "building" :            	"Butler Library",
            "campus" :			"Morningside",
            "room" :				"505",
            "email" :         "jonah@ccnmtl.columbia.edu",
            "last" :       	"Bossewitch",
            "first" :			"Jonah",
            "phone" :         "212 854-1815",
            "title" :         "Senior Technical Architect",
            "group" : 		"Technology",
            "bio" : 			"Jonah works as a Technology and Programmer Analyst at CCNMTL. He works closely with the Educational Technologists, Webmasters, and Programmers. He is also pursuing a graduate degree in <a target='_blank' href='http://www.tc.edu/mst/ccte/'>Communication and Education</a> at Teachers College. Jonah has an extensive background in software architecture, design, and development. Prior to joining the center, he was the lead developer at <a href='http://www.abstractedge.com' target='_blank'>Abstract Edge</a>, an interactive marketing firm which serviced both non-profit and corporate clients.  He was also a senior developer at <a href='http://www.mamamedia.com' target='_blank'>MaMaMedia</a>, a children's educational Web site.  He is an open source contributor whose technical interests include Linux, Python, and Content Management. He graduated from Princeton University ('97) with a BA in Philosophy, and a certificate in Computer Science.  He enjoys bike riding, hanging out in Central Park, playing the bass, and scuba diving.",
            "imageURL" :              "http://ccnmtl.columbia.edu/web/assets/headshots/Bossewitch.jpg"
        },
        {   "type" :          "Staff",
            "label" :         "Michelle V. Hall",
            "building" :            	"Armory",
            "campus" :			"CUMC",
            "room" :				"200 Level",
            "email" :         "mvh7@columbia.edu",
            "last" :       	"Hall",
            "first" :			"Michelle",
            "phone" :          "646 772-8612",
            "title" :          "Educational Technologist I",
            "group" : 		  "Education",
            "bio" : 			"Michelle Hall joins the CCNMTL team as an Educational Technologist at the Medical Center office. For the last year and a half Michelle worked as an instructional designer on web based learning products for Citigroup and McGraw Hill. Prior to that, she worked with us at CCNMTL as a part-timer. Michelle has a BSc. in Biology and received her M.A. in Computing and Education from Teachers College. She is currently pursuing the Ed.M in Cognitive Studies in Education there.",
            "imageURL" :              "http://ccnmtl.columbia.edu/web/assets/headshots/MHall.jpg"
        },
        {   "type" :          "Staff",
            "label" :         "Alice Cox",
            "building" :      "Lewisohn Hall",
            "campus" :			"Morningside",
            "room" :				"603",
            "email" :         "acox@ccnmtl.columbia.edu",
            "last" :       	"Cox",
            "first" :			"Alice",
            "phone" :          "212 854-1851",
            "title" :          "Educational Technologist II",
            "group" : 		  "Education",
            "bio" : 			"Alice Cox joined CCNMTL in July 2006 as an Educational Technologist. <!--She works primarily with the School of Engineering and many of the science departments at Columbia University to facilitate faculty projects.-->  She was previously a Publication Manager with the MIT OpenCourseWare project, where she was responsible for recruiting, developing, and managing projects for presenting MIT course materials from the School of Science for open access publication to the world. She also brings five years of experience from the biotech industry, where she worked as a technical writer and software engineer specializing in database software for companies such as NeoGenesis, Inc., Wyeth BioPharma, and Millennium Pharmaceuticals. Alice is an avid filmmaker whose work has been featured in festivals throughout New England.",
            "imageURL" :              "http://ccnmtl.columbia.edu/web/assets/headshots/cox.jpg"
        },
        {   "type" :          "Staff",
            "label" :         "Frank A. Moretti",
            "building" :      "Lewisohn Hall",
            "campus" :			"Morningside",
            "room" :				"603",
            "email" :         "fmoretti@columbia.edu",
            "last" :       	"Moretti",
            "first" :			"Frank",
            "phone" :          "212 854-1692",
            "title" :          "Executive Director",
            "group" : 		  ["Management", "Education"],
            "bio" : 			"Frank Moretti is co-founder of the Columbia Center for New Media Teaching and Learning, for which he provides pedagogical, strategic and managerial leadership. In addition to defining the goals and disseminating the CCNMTL message on campus, Frank serves as Professor of Communications, Computing and Technology at Teachers College. Prior to joining Teachers College, Frank served as the Associate Headmaster at the Dalton School, where he was also Executive Director of their New Laboratory for Teaching and Learning, which he co-founded in 1989, and of the internationally known Dalton Technology Plan.  His many degrees include a Ph.D. in History and an M. Phil from Columbia University, an M.Ed. from Teachers College and a B.A. in Greek and Latin from St. Bonaventure University.  Frank is recognized as one of America's leading theorists and practitioners in the use of digital technology in education.",
            "imageURL" :              "http://ccnmtl.columbia.edu/web/assets/headshots/Moretti.jpg"
        },
        {   "type" :          "Staff",
            "label" :         "Teresa Gonzalez",
            "building" :      "Lewisohn Hall",
            "campus" :			"Morningside",
            "room" :				"603",
            "email" :         "teresa@columbia.edu",
            "last" :       	"Gonzalez",
            "first" :			"Teresa",
            "phone" :          "212 854-1692",
            "title" :          "Executive Assistant",
            "group" : 		  "Management",
            "bio" : 			"Teresa provides administrative and executive level support to the Executive Director including scheduling meetings and coordinating activities with faculty, national and international corporate executives, and senior-level University officials at Columbia and elsewhere. Teresa has twenty-eight years of successful administrative/secretarial experience. Before CCNMTL, she worked at the Institute for Learning Technologies at Teachers College and The Dalton School.  She attended New York Bilingual Institute for Secretarial Science, Taylor Business Institute for Business Management and Marymount Manhattan College.",
            "imageURL" :              "http://ccnmtl.columbia.edu/web/assets/headshots/na.jpg"
        },
        {   "type" :      "Staff",
            "label" :     "Daniel Beeby",
            "building" :  "Butler Library",
            "campus" :	"Morningside",
            "room" :		"505",
            "email" :     "dbeeby@columbia.edu",
            "last" :      "Beeby",
            "first" :		"Daniel",
            "phone" :     "212 854-9640",
            "title" :     "Associate Director of Services, Lead Educational Technologist",
            "group" :     "Education",
            "bio" : 			"Dan serves the Center for New Media Teaching and Learning as Associate Director for Services and as an Educational Technologist.  Primarily, he facilitates faculty partners' projects and works as the Center's representative to the CourseWorks development team. Formerly, Dan was the Technical Specialist for the Mellon Tri-College Language Project at Haverford, Bryn Mawr and Swarthmore colleges where he worked with faculty on dozens of educational technology projects; offered presentations and workshops at numerous language conferences; and developed the &quote;Makers&quote; interactive-exercise creation tool. Before that Dan taught English at the Kaunas University of Technology in Lithuania and German at Michigan State University.  He is currently pursuing an advanced degree at Teachers College.",
            "imageURL" :              "http://ccnmtl.columbia.edu/web/assets/headshots/Beeby.jpg"
        },
        {   "type" :          "Staff",
            "label" :         "Ryan Kelsey",
            "building" :   "Lewisohn Hall",
            "campus" :	 "Morningside",
            "room" :		 "603",
            "email" :      "ryan@columbia.edu",
            "last" :       "Kelsey",
            "first" :		 "Ryan",
            "phone" :      "212 854-0209",
            "title" :      "Associate Director of Education and Research",
            "group" : 	 ["Management", "Education"],
            "bio" : 		 "Ryan Kelsey is the Associate Director of Education and Research for CCNMTL, where he focuses on the overall educational direction and leading the design research and evaluation efforts for the Center's full range of services and projects. Prior to becoming an Associate Director, Ryan spent six years as a Project Manager and Educational Technologist for CCNMTL. Ryan has directed a wide assortment of projects, mostly focused in science and simulations, including the award-winning <i>Brownfield Action</i> environmental science simulation and Columbia College's new <i>Frontiers of Science</i> core course. Ryan is also an Adjunct Assistant Professor for Columbia College's <i>Frontiers of Science</i> course and the department of Mathematics, Science, and Technology in Education at Teachers College. He earned his Ed.D. in 2003 (and M.A. in 1999) from TC. He received his B.S. in biology from Santa Clara University.",
            "imageURL" :              "http://ccnmtl.columbia.edu/web/assets/headshots/Kelsey.jpg"
        },
        {   "type" :       "Staff",
            "label" :      "Eric Mattes",
            "building" :   "Butler Library",
            "campus" :	"Morningside",
            "room" :		"505",
            "email" :     "em2140@columbia.edu",
            "last" :      "Mattes",
            "first" :		"Eric",
            "phone" :     "212 854-3928",
            "title" :      "Programmer Analyst",
            "group" :     "Technology",
            "bio" : 		"Eric Mattes, a native New Yorker, graduated in 2002 from Connecticut College with a B.A. in Computer Science and a minor in Chinese Studies. Eric worked part-time at CCNMTL until he started full-time work during the summer of 2002. Eric designs and develops Web applications for the CCNMTL and has done work in languages including Flash, Java, Python, and Perl.",
            "imageURL" :              "http://ccnmtl.columbia.edu/web/assets/headshots/Mattes.jpg"
        },
        {   "type" :       "Staff",
            "label" :      "Zarina Mustapha",
            "building" :   "Butler Library",
            "campus" :	"Morningside",
            "room" :		"505",
            "email" :     "zarina@columbia.edu",
            "last" :      "Mustapha",
            "first" :		"Zarina",
            "phone" :     "212 854-2390",
            "title" :      "Webmaster",
            "group" :     ["Editorial and Design", "Technology"],
            "bio" : 		"Zarina works with educational technologists and faculty to identify sense out of information chaos, and provides or recommends solutions for information architecture, content management,  back-end development and user interface. She received her B.S. and M.S. in Engineering from Columbia University School of Engineering and Applied Science.",
            "imageURL" :              "http://ccnmtl.columbia.edu/web/assets/headshots/na.jpg"
        },
        {   "type" :       "Staff",
            "label" :      "Stephanie Ogden",
            "building" :   "Butler Library",
            "campus" :	"Morningside",
            "room" :		"505",
            "email" :     "sogden@columbia.edu",
            "last" :      "Ogden",
            "first" :		"Stephanie",
            "phone" :     "212 854-1814",
            "title" :      "Senior Digital Media Specialist",
            "group" :     "Digital Media",
            "bio" : 		"Stephanie manages a team of three full-time and several part-time audio-visual specialists.  She oversees all CCNMTL video projects including events, interviews, seminars and simulations and handles all post-production video work, including editing, titling, encoding, compression and live web broadcasts. Stephanie worked as a freelance video producer for several years and also worked at Worldview International Foundation (Nepal), UNICEF (Nepal) and the Columbia Office Public Affairs, where she initiated and directed their Video Bureau. Stephanie received her M.A. in Broadcast Television and Video from San Francisco State University.",
            "imageURL" :              "http://ccnmtl.columbia.edu/web/assets/headshots/Ogden.jpg"
        },
        {   "type" :       "Staff",
            "label" :      "Anders Pearson",
            "building" :   "Butler Library",
            "campus" :	"Morningside",
            "room" :		"505",
            "email" :     "anders@columbia.edu",
            "last" :      "Pearson",
            "first" :		"Anders",
            "phone" :     "212 854-1813",
            "title" :      "Programmer Analyst",
            "group" :     "Technology",
            "bio" : 		"Anders develops Web-based and GUI applications and provides programming and technology support for CCNMTL, specializing in Python, Perl, XML, XSLT, GNU/Linux, and database design.  He is a graduate of Columbia University, where he received his B.S. in Computer Engineering. He also holds a B.S. in Engineering from Bates College and studied Chinese at the University of Nanjing. Anders fights to keep the Web open to all as a member of the Web Standards Project",
            "imageURL" :              "http://ccnmtl.columbia.edu/web/assets/headshots/na.jpg"
        },
        {   "type" :       "Staff",
            "label" :      "Michael R. Deleon",
            "building" :   "Butler Library",
            "campus" :	"Morningside",
            "room" :		"505",
            "email" :     "mrd71@columbia.edu",
            "last" :      "Deleon",
            "first" :		"Michael",
            "phone" :     "646 678-0553",
            "title" :      "Media and Production Coordinator",
            "group" :     "Digital Media",
            "bio" : 		"",
            "imageURL" :              "http://ccnmtl.columbia.edu/web/assets/headshots/Deleon.jpg"
        },
        {   "type" :       "Staff",
            "label" :      "Catherine Jhee",
            "building" :   "Butler Library",
            "campus" :	"Morningside",
            "room" :		"505",
            "email" :     "cjj2104@columbia.edu",
            "last" :      "Jhee",
            "first" :		"Catherine",
            "phone" :     "212 854-1867",
            "title" :     "Editorial Producer II",
            "group" :     "Editorial and Design",
            "bio" : 		"Catherine joined CCNMTL as Editorial Producer in Fall 2004.  She comes to CCNMTL from the American Museum of Natural History's Science Bulletins, where she wrote and produced weekly science news updates. Previously, she worked at Picture Projects on documentary web sites, including 360degrees.org, an examination of the American criminal justice system. Catherine received her A.B. from Duke University and an M.A.H. from the University at Buffalo in Comparative Literature and Media Studies.",
            "imageURL" :              "http://ccnmtl.columbia.edu/web/assets/headshots/Jhee.jpg"
        },
        {   "type" :       "Staff",
            "label" :      "Elizabeth Day",
            "building" :   "Butler Library",
            "campus" :	"Morningside",
            "room" :		"505",
            "email" :     "ed2198@columbia.edu",
            "last" :      "Day",
            "first" :		"Liz",
            "phone" :     "212 854-1853",
            "title" :      "Creative Director",
            "group" :     "Editorial and Design",
            "bio" : 		"Liz Day joined the CCNMTL as Creative Director in December 2004. Liz is charged with building on the visual design and functionality of CCNMTL projects, as well as helping to increase the Center's brand visibility and recognition. Before coming to Columbia, Liz spent seven years in various design-and technology- related positions at American International Group (AIG), including work within the Corporate Training Department, where she developed expertise in interactive educational projects and tools. Liz has also done work for a variety of other clients, from Bank Street Books to the Cartoon Network. A former circus performer, Liz holds a B.F(unny).A. from Ringling Bros. and Barnum & Bailey Clown College, as well as a B.A. in American Studies and Studio Art from Tufts University. Liz is an avid world traveler, as well as a two-time winner of the Coney Island Mermaid Parade and a member of an inter- racial, inter-religious gospel choir.",
            "imageURL" :              "http://ccnmtl.columbia.edu/web/assets/headshots/Day.jpg"
        },
        {   "type" :       "Staff",
            "label" :      "Michael Preston",
            "building" :   "Butler Library",
            "campus" :	"Morningside",
            "room" :		"505",
            "email" :     "mpreston@ccnmtl.columbia.edu",
            "last" :      "Preston",
            "first" :		"Michael",
            "phone" :     "212 854-0208",
            "title" :     "Educational Technologist I",
            "group" :     "Education",
            "bio" : 		"Michael joined CCNMTL in October 2003 and is primarily responsible for the VITAL project, a multi-disciplinary, Web-based learning environment for video analysis and communication. He is currently pursuing a doctorate in Cognitive Studies from Teachers College, working with Prof. Herbert Ginsburg. Previously, he was Program Officer for Technology at New Visions for Public Schools, a nonprofit organization dedicated to public education reform in New York City. He also worked for the Japan Foundation Center for Global Partnership (CGP), where he administered grants for K-12 curriculum development and teacher training projects in the US and Japan. Michael received a BA in East Asian Studies from Harvard University.",
            "imageURL" :              "http://ccnmtl.columbia.edu/web/assets/headshots/Preston.jpg"
        },
        {   "type" :       "Staff",
            "label" :      "Jessica Rowe",
            "building" :   "Lewisohn Hall",
            "campus" :	 "Morningside",
            "room" :		 "603",
            "email" :     "jr2502@columbia.edu",
            "last" :      "Rowe",
            "first" :		"Jessica",
            "phone" :     "212 854-0207",
            "title" :     "Associate Educational Technologist",
            "group" :     "Education",
            "bio" : 		"Jessica joins CCNMTL as an Associate Educational Technologist.  She previously worked in instructional technology at Northwestern University in Evanston, Illinois. In addition to her work in education, Jessica is an artist and photographer.  She has had exhibitions at the Museum of Contemporary Photography and the Art Institute of Chicago, and until recently was a participant in the Midwest Photographers Project and an instructor at Columbia College, Chicago. Jessica received her BA from Smith College and her MDes from the Institute of Design (part of the Illinois Institute of Technology) in Chicago. ",
            "imageURL" :              "http://ccnmtl.columbia.edu/web/assets/headshots/na.jpg"
        },
        {   "type" :       "Staff",
            "label" :      "Eddie Rubeiz",
            "building" :   "Butler Library",
            "campus" :	"Morningside",
            "room" :		"505",
            "email" :     "eddie@ccnmtl.columbia.edu",
            "last" :      "Rubeiz",
            "first" :		"Eddie",
            "phone" :     "212 854-1869",
            "title" :      "Programmer Analyst",
            "group" :     "Technology",
            "bio" : 		"Eddie Rubeiz joins CCNMTL after working as a web/database developer at a variety of companies in the financial, pharmaceutical and music industries. He holds an undergraduate degree in classical literature from Princeton, and maintains an interest in languages of all types, obscure ones in particular. He's also an avid musician and cyclist.",
            "imageURL" :              "http://ccnmtl.columbia.edu/web/assets/headshots/rubeiz.jpg"
        },
        {   "type" :       "Staff",
            "label" :      "Schuyler Duveen",
            "building" :   "Butler Library",
            "campus" :	"Morningside",
            "room" :		"505",
            "email" :     "sky@columbia.edu",
            "last" :      "Duveen",
            "first" :		"Schuyler",
            "phone" :     "212 854-7076",
            "title" :      "Programmer Analyst",
            "group" :     "Technology",
            "bio" : 		"Schuyler joins CCNMTL as a programmer, where he develops Web and GUI applications. He has a B.A. from Columbia, where he studied Math and Electrical Engineering, but also enjoyed some Derrida and Durkheim.  He is currently working on a couple of artistic projects related to visual ontologies. He began his career at Columbia at CUIT.",
            "imageURL" :              "http://ccnmtl.columbia.edu/web/assets/headshots/Duveen.jpg"
        },
        {   "type" :       "Staff",
            "label" :      "Mark Phillipson",
            "building" :   "Lewisohn Hall",
            "campus" :	 "Morningside",
            "room" :		 "603",
            "email" :     "mlp55@columbia.edu",
            "last" :      "Phillipson",
            "first" :		"Mark",
            "phone" :     "212 854-0210",
            "title" :      "Coordinator of Teaching, Learning, and Library Services",
            "group" :     "Education",
            "bio" : 		"Mark joined the Center for New Media Teaching and Learning as Coordinator of Teaching, Learning, and Library Services in May 2006.   His variegated background helps him facilitate new partnership opportunities for CCNMTL, faculty, and library services.\nPreviously, he was an Assistant Professor of English at Bowdoin College, where he developed early models of scholarly wikis to supplement his teaching.   Mark has taught courses in subjects such as nineteenth-century British literature, narrative theory, and gay studies, and he has published a number of articles on romanticism.  He has also worked as a web editor and a network programmer at Excite@Home.\nConvinced of the importance of creative library support for digital humanties projects, Mark recently earned a degree in library science.  He was designated an Association of Research Libraries Academy Fellow in 2005.   Mark holds a PhD from the University of California, Berkeley, an MLIS from Simmons College, and a B.A. in English from Columbia College.",
            "imageURL" :              "http://ccnmtl.columbia.edu/web/assets/headshots/na.jpg"
        },
        {   "type" :       "Staff",
            "label" :      "Martin Capella",
            "building" :   "Butler Library",
            "campus" :	"Morningside",
            "room" :		"505",
            "email" :     "martin@ccnmtl.columbia.edu",
            "last" :      "Capella",
            "first" :		"Martin",
            "phone" :     "212 854-1868",
            "title" :      "Senior Technical Specialist",
            "group" :     "Technology",
            "bio" : 		"Martin joins CCNMTL as Senior Technical Specialist, where he provides computer hardware, software, and network support for the Center's mixed environment of Macs, Linux, and Windows. He works with programmers, educational technologists, faculty, and other stakeholders to plan and implement new media technologies for education. Formerly a Mac Genius at the SoHo Apple Store, Martin excelled at customer service, training, and integration. He also worked in web design and development after receiving his B.A. in Photography from Empire State College.",
            "imageURL" :              "http://ccnmtl.columbia.edu/web/assets/headshots/headshot.jpg"
        },
        {   "type" :       "Staff",
            "label" :      "M. Josh Stanley",
            "building" :   "Lewisohn Hall",
            "campus" :	 "Morningside",
            "room" :		 "603",
            "email" :     "josh@ccnmtl.columbia.edu",
            "last" :      "Stanley",
            "first" :		"Josh",
            "phone" :     "212 854-0206",
            "title" :      "Educational Technologist I",
            "group" :     "Education",
            "bio" : 		"Josh Stanley joins the Center as an Educational Technologist I. He was formerly the multimedia producer for the University of Denver, where he worked with faculty on  educational technology projects. Recently, he was the director of multimedia at CCA Advertising in New York where he produced media for national and international companies. Josh received masters degrees from the University of Denver in Mass Communications and Digital Media Studies.  He is currently at TC working on his Ed.D. in Instructional Technology and Media. ",
            "imageURL" :              "http://ccnmtl.columbia.edu/web/assets/headshots/na.jpg"
        },
        {   "type" :       "Staff",
            "label" :      "Peter B. Kaufman",
            "building" :   "Lewisohn Hall",
            "campus" :	 "Morningside",
            "room" :		 "603",
            "email" :     "pkaufman@ccnmtl.columbia.edu",
            "last" :      "Kaufman",
            "first" :		"Peter",
            "phone" :     "212 854-2860",
            "title" :      "Associate Director",
            "group" :     "Management",
            "bio" : 		"Peter B. Kaufman is a documentary producer and the founder and president of <a href=\"http://www.intelligenttelevision.com\" target=\"_blank\">Intelligent Television</a>. He currently serves as project director of the <a href=\"http://www.hewlett.org/Programs/Education/OER\" target=\"_blank\">Open Education Video Project</a> for the William and Flora Hewlett Foundation; an expert consultant on access issues for the <a href=\"http://www.loc.gov/film\" target=\"_blank\">Library of Congress Division of Motion Picture, Broadcasting, and Recorded Sound</a>; and a member of the <a href=\"http://www.acls.org/cyberinfrastructure/cyber.htm\" target=\"_blank\">American Council of Learned Societies National Commission on Cyberinfrastructure in the Humanities</a>, funded by the Andrew W. Mellon Foundation.  He also serves as a Senior Fellow at the World Policy Institute in New York and a member of the Editorial Board of the Institute's <a href=\"http://www.worldpolicy.org/journal/\" target=\"_blank\">World Policy Journal</a>.\nPreviously, Mr. Kaufman served as founder and president of TV Books, where he negotiated and concluded publishing deals with television networks, independent producers, literary agents, and authors worldwide.  He sold majority interest in TV Books to Broadway Video, Lorne Michaels's television and film company.  Mr. Kaufman also has served as director of strategic initiatives at Innodata Isogen; as founder and executive director of PUBWATCH, a nonprofit organization supporting the publishing industries in Central and Eastern Europe; and as director of publications at the Institute for EastWest Studies.  Educated at Cornell University and Columbia University's W. Averell Harriman Institute for Advanced Study of the Soviet Union, he has written for Publishers Weekly, Scholarly Publishing, Slavic Review, Russian History, The New York Times, The Nation, First Monday, Information Outlook, the Times Literary Supplement and International Book Publishing: An Encyclopedia.",
            "imageURL" :              "http://ccnmtl.columbia.edu/web/assets/headshots/kaufman.jpg"
        },
        {   "type" :       "Staff",
            "label" :      "J. Peter Siriprakorn",
            "building" :   "Butler Library",
            "campus" :	"Morningside",
            "room" :		"505",
            "email" :     "jps2131@columbia.edu",
            "last" :      "Siriprakorn",
            "first" :		"Peter",
            "phone" :     "212 854-9058",
            "title" :      "Technical Specialist B",
            "group" :     "Education",
            "bio" : 		"Prior to joining CCNMTL, Peter provided technical support services at the NYU School of Law and The University of Chicago. He was also a research assistant at the Center for Highly Interactive Computing in Education at The University of Michigan, where he developed PalmOS applications to support the integration of PalmOS handheld devices into K-12 classroom curriculums. \nJ. Peter studied English and Computer Science at The University of Michigan and is just 30 pages shy of an M.A. in Humanities from The University of Chicago. His interests include psychoanalysis, critical theory, and poststructuralist philosophies of difference and becoming. In his off hours, J. Peter enjoys techno, microhouse, and celebrating all things Detroit.",
            "imageURL" :              "http://ccnmtl.columbia.edu/web/assets/headshots/siriprakorn.jpg"
        },
        {   "type" :       "Staff",
            "label" :      "Tucker Harding",
            "building" :   "Lewisohn Hall",
            "campus" :	 "Morningside",
            "room" :		 "603",
            "email" :     "tucker@ccnmtl.columbia.edu",
            "last" :      "Harding",
            "first" :		"Tucker",
            "phone" :     "212 854-1852",
            "title" :      "Educational Technologist I",
            "group" :     "Education",
            "bio" : 		"Tucker joined CCNMTL in September 2006 after spending five years as a project manager for some of the major wireless telecom players in China. His academic background in East Asian Studies coupled with a strong personal interest in Asian cultures served him well while living and working in both China and Japan.\n Led by an interest in education, he began designing and managing training programs using proprietary training tools for corporate managers. Shortly thereafter, he found fulfillment in teaching a number of courses in business and spoken English at local colleges in Xiamen and Beijing. He comes to CCNMTL as an Educational Technologist focusing on the use of new media to enhance the effectiveness of courses that include cultural, linguistic and business-related components. \nTucker speaks Mandarin Chinese and is a member of the Chinese Wushu Association.  He has successive tournament victories in both San Shou and full-contact mixed martial arts in China and Japan, but his fighting days appear to be over as his obsession with improving educational systems has finally won his devotion.",
            "imageURL" :              "http://ccnmtl.columbia.edu/web/assets/headshots/harding.jpg"
        },
        {   "type" :       "Staff",
            "label" :      "Nitin Gumaste",
            "building" :   "Armory",
            "campus" :	"CUMC",
            "room" :		"200 Level",
            "email" :     "nitin@ccnmtl.columbia.edu",
            "last" :      "Gumaste",
            "first" :		"Nitin",
            "phone" :     "646 772-8608",
            "title" :      "Associate Educational Technologist",
            "group" :     "Education",
            "bio" : 		"Nitin recently completed his MA from Ball State University, where he specialized in Digital Storytelling. His thesis involved studying the paradigms of the video iPod and other portable entertainment media as a means of episodic entertainment. Concurrently, he also worked as technical consultant for the interactive news television project at <a href=\"http://newslinkindiana.blogspot.com\" target=\"_blank\">NewsLink Indiana</a>. This was an experiment in presenting news in a radical way, combining the ease of watching television with the power and access of the Internet. \nNitin also has a BA from the University of Denver, majoring in Digital Media Studies and Communication. Working on numerous academic projects here is what sparked his interest in educational technology. \nIn his spare time, he enjoys reading, video editing, listening to music, spending time with his niece, and all things Colorado and his native country, India.",
            "imageURL" :              "http://ccnmtl.columbia.edu/web/assets/headshots/gumaste.jpg"
        },
        {   "type" :       "Staff",
            "label" :      "Briana Ferrigno",
            "building" :   "Butler Library",
            "campus" :	"Morningside",
            "room" :		"505",
            "email" :     "briana@ccnmtl.columbia.edu",
            "last" :      "Ferrigno",
            "first" :		"Briana",
            "phone" :     "212 854-7783",
            "title" :      "Associate Editorial Producer",
            "group" :     "Editorial and Design",
            "bio" : 		"Briana joins CCNMTL after working in the online media industry for two years. She was formally an account manager at the digital marketing agency, Avenue A-Razorfish, where she developed, analyzed and optimized media and search-engine advertising campaigns for Starwood Hotels. Briana received her BA in Communications and Electronic Media from the George Washington University. She was also a competitive figure skater for 10 years and an avid lacrosse player.",
            "imageURL" :              "http://ccnmtl.columbia.edu/web/assets/headshots/na.jpg"
        },
        {   "type" :       "Staff",
            "label" :      "Jennifer Spiegler",
            "building" :   "Lewisohn Hall",
            "campus" :	 "Morningside",
            "room" :		 "603",
            "email" :     "jen@ccnmtl.columbia.edu",
            "last" :      "Spiegler",
            "first" :		"Jennifer",
            "phone" :     "212 854-9105",
            "title" :      "Assistant Director for Strategic Initiatives",
            "group" :     "Management",
            "bio" : 		"",
            "imageURL" :              "http://ccnmtl.columbia.edu/web/assets/headshots/na.jpg"
        }
      ]
       }
        
